version: '3.9'

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      target: dev
    container_name: php
    command: "sh -c 'mkdir -p /root/.ssh && cp -r /root/host-ssh-keys/* /root/.ssh && chown -R root:root /root/.ssh && php-fpm'"
    environment:
      ENABLE_MODULES: apcu
      STARTUP_COMMAND_1: composer install
    volumes:
      - "../webprod.com/:/var/www/webprod.com:delegated"
      - "~/.ssh:/root/host-ssh-keys:ro,delegated"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"
    expose:
      - 9000
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "83:80"
      - "443:443"
    volumes:
      - "./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - "./config/nginx/ssl/:/etc/nginx/ssl/"
      - "./config/nginx/snippets/:/etc/nginx/snippets/"

      - "./var/log/:/var/log"
      - "../webprod.com/:/var/www/webprod.com"

    depends_on:
      - php
  mysql:
    image: mysql:8.0
    container_name: mysql
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    env_file:
      - ./.env
    expose:
      - 6379